# Generated by Django 5.2.3 on 2025-07-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
